from django.db import models

# Create your models here.
class SASD_Old_Format(models.Model):
    SEQ = models.IntegerField()
    DateTime = models.DateTimeField()
    Name = models.TextField()
    Prd_ID = models.TextField()
    Purchase_Cost = models.DecimalField(max_digits=20, decimal_places=2)
    Purchase_Qtt = models.IntegerField()
    Total_Revenue = models.IntegerField()
    Sold_Qtt = models.IntegerField() #this is not net QTT
    PV = models.IntegerField()
    UV = models.IntegerField()
    Single_Cust_Price = models.DecimalField(max_digits=20, decimal_places=2)
    Rate_of_Conv = models.DecimalField(max_digits=5, decimal_places=2)
    Nm_of_Cust_Pchs = models.IntegerField()
    Sold_Pctge = models.DecimalField(max_digits=5, decimal_places=2)
    Out_of_Stock = models.BooleanField()
    SKU_OOS_Rate = models.DecimalField(max_digits=5, decimal_places=2) #OOS stands for out of stock
    Sold_Out_Dur = models.DateTimeField()
    Reject_Qtt = models.IntegerField()
    Reject_Rate = models.DecimalField(max_digits=5, decimal_places=2)
    Reject_Amt = models.DecimalField(max_digits=20, decimal_places=2)
    Return_Qtt = models.IntegerField()
    Return_Rate = models.DecimalField(max_digits=5, decimal_places=2)
    Return_Amt = models.DecimalField(max_digits=20, decimal_places=2)
    RFRT_Qtt = models.IntegerField()
    RFRT_Rate = models.DecimalField(max_digits=5, decimal_places=2)
    RFRT_Amt = models.DecimalField(max_digits=20, decimal_places=2)
    
    
class SASD_New_Format(models.Model):
    SEQ = models.IntegerField()
    DateTime = models.DateTimeField()
    Name = models.TextField()
    Brand = models.TextField()
    Prd_ID = models.TextField()
    Bar_Code = models.TextField()
    Purchase_Cost = models.DecimalField(max_digits=20, decimal_places=2)
    Recomd_Grade = models.CharField(max_length=2)
    Sale_Site = models.TextField()
    Act_Name = models.TextField()
    Date_One = models.DateField()
    Original_Price = models.DecimalField(max_digits=20, decimal_places=2)
    Pchs_Discnt = models.DecimalField(max_digits=5, decimal_places=2)
    Sale_Period = models.IntegerField()
    First_Categ = models.CharField(max_length=15) 
    Second_Categ = models.CharField(max_length=15)
    Third_Categ = models.CharField(max_length=15)
    Material = models.TextField()
    Size = models.TextField()
    Pchs_Qtt= models.IntegerField()
    Value_of_Pchs = models.DecimalField(max_digits=20, decimal_places=2)
    Sale_Price = models.DecimalField(max_digits=20, decimal_places=2)
    Sale_Discnt = models.DecimalField(max_digits=5, decimal_places=2)
    Sold_Qtt = models.IntegerField() #this is not net QTT
    Net_Sold_Qtt = models.IntegerField()
    Revenue = models.DecimalField(max_digits=20, decimal_places=2)
    Net_Revenue = models.DecimalField(max_digits=20, decimal_places=2) # this is Revenue - Har_Cut_Amt
    Hair_Cut_Amt = models.DecimalField(max_digits=20, decimal_places=2)
    Sold_Rate_In_Amt = models.DecimalField(max_digits=5, decimal_places=2)
    Sold_Rate_In_Qtt = models.DecimalField(max_digits=5, decimal_places=2)
    PV = models.IntegerField()
    UV = models.IntegerField()
    Nm_of_Cust_Pchs = models.IntegerField()
    Rate_of_Conv = models.DecimalField(max_digits=5, decimal_places=2)
    Add_To_Cart_No = models.IntegerField()
    Third_Categ_Sold_Qtt = models.IntegerField()
    Third_Categ_Sold_Amt = models.DecimalField(max_digits=20, decimal_places=2)
    Third_Categ_Sold_Ptg = models.DecimalField(max_digits=5, decimal_places=2)
    Third_Categ_Sold_SKU = models.IntegerField()
    First_Day_Sold_Qtt = models.IntegerField()
    First_Day_Sold_Ptg = models.DecimalField(max_digits=5, decimal_places=2)
    SKU_Rank = models.IntegerField()
    Mob_Sold_Qtt = models.IntegerField()
    Mob_Sold_Amt = models.DecimalField(max_digits=20, decimal_places=2)
    Mob_Ptg_of_Total_Sold_Qtt = models.DecimalField(max_digits=5, decimal_places=2)
    Mob_Ptg_of_Total_Sold_Amt = models.DecimalField(max_digits=5, decimal_places=2)
    